### ISSUE TITLE
readme 介绍， 最好采用和其他模板一样做法的 s init

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/start-puppeteer#2]
![image](https://user-images.githubusercontent.com/10919599/128847208-c4cbc38c-725e-4dc9-82a1-1f5a833b3e27.png)

使用了这个以后， 应该就没有  src 目录了， 对应  readme 中的 cd 也需要改下

**Comment by alapha23** [comment]
Fixed in #7 . Cheers xd
