### ISSUE TITLE
Custom Contaier 不需要这个 funfile

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/start-puppeteer#3]
![image](https://user-images.githubusercontent.com/10919599/128847547-a4e1c923-69d8-485c-a16b-64dc2e9aee07.png)

**Comment by alapha23** [comment]
Good point! Fixed in PR [Fix nodejs vpc config and container directory orders](https://github.com/devsapp/start-puppeteer/pull/6). Thank you xd.
