### ISSUE TITLE
custom container 直接 s build 有错误

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/start-puppeteer#4]
![image](https://user-images.githubusercontent.com/10919599/128847807-a60a6e3d-9302-47f0-9578-b4ff8d1de78d.png)

1. 通过情况下， Dockerfile 应该和 s.yaml 是平级目录
2. 
- 2.1 用户直接使用你的 public 镜像， 直接 s deploy 即可
- 2.2 用户想自己基于 docker file 编译镜像，并且自动推送到自己的 acr 仓库， 然后再部署， 需要介绍下这个命令 ·s deploy --push-registry acr-internet --use-local -y`

**Comment by alapha23** [comment]
For 1, fix has been proposed in PR [Fix nodejs vpc config and container directory orders](https://github.com/devsapp/start-puppeteer/pull/6).

For 2, as long as aliyun container registry is activated, with active namespace and repo names, `s deploy` should push the docker image to user's repo. As far as I'm concerned, there isn't any public image that I built intentionally for this project. Please correct me if I misunderstood anything. Thanks.

**Comment by alapha23** [comment]
Sorry for 2 I got it wrong. Will fix in pr #7
